Repository microsoft/vscode-flake8, pull requests merged in 2022-10, with the labels that each got.

#55 Update packages.
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: debt

#59 Update to use latest python environment APIs
  package-lock.json
  package.json
  src/common/python.ts
Labels: feature-request

#64 Update CHANGELOG.md
  CHANGELOG.md
Labels: no-changelog

#65 Added quick fix for "tab after keyword" (E273)
  bundled/tool/server.py
  src/test/python_tests/test_code_actions.py
Labels: feature-request

#69 Update packages.
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: no-changelog
