Repository microsoft/vscode-flake8, pull requests merged in 2022-09, with the labels that each got.

#30 Code action support to provide command quick fixes.
  bundled/tool/server.py
  package-lock.json
  package.json
  src/test/python_tests/lsp_test_client/session.py
  src/test/python_tests/requirements.txt
  src/test/python_tests/test_code_actions.py
Labels: feature-request

#32 Update packages and fix build.
  package-lock.json
  package.json
Labels: debt

#43 Reorder flake8 settings in package.json in an alphabetical order.
  package.json
Labels: debt

#44 Added quick fix for "tab before keyword" warning.
  bundled/tool/server.py
  src/test/python_tests/test_code_actions.py
Labels: feature-request

#48 Bug fixes for file only scenario.
  bundled/tool/server.py
  src/common/utilities.ts
  src/extension.ts
Labels: bug
