Repository microsoft/vscode-flake8, pull requests merged in 2023-06, with the labels that each got.

#164 Engineering - update pre-release pipeline
  build/azure-pipeline.pre-release.yml
Labels: debt

#166 Engineering - add TSAOptions
  build/azure-pipeline.stable.yml
Labels: no-changelog

#169 Mark virtual workspaces as unsupported in package.json
  package.json
Labels: bug

#154 Update to node 16, dependencies and fixes from other extensions
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  bundled/tool/lsp_runner.py
  bundled/tool/lsp_server.py
  package-lock.json
  package.json
  requirements.txt
  src/common/settings.ts
  src/test/python_tests/requirements.txt
Labels: debt

#165 Remove incorrect statement from README
  README.md
Labels: bug

#176 Add code action for E242
  bundled/tool/lsp_server.py
  src/test/python_tests/test_code_actions.py
Labels: feature-request
