Repository microsoft/vscode-flake8, pull requests merged in 2023-10, with the labels that each got.

#234 Update to latest version of packages and python
  .github/actions/build-vsix/action.yml
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  README.md
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  bundled/tool/lsp_server.py
  noxfile.py
  package-lock.json
  package.json
  requirements.in
  requirements.txt
  runtime.txt
  src/common/python.ts
  src/extension.ts
  src/test/python_tests/requirements.in
  src/test/python_tests/requirements.txt
Labels: debt

#235 Update version for release
  package-lock.json
  package.json
Labels: no-changelog

#223 Code action test should wait for diagnostics
  src/test/python_tests/test_code_actions.py
Labels: debt, ghc-osd

#236 Update main to next pre-release version
  package-lock.json
  package.json
Labels: no-changelog

#239 Adds ignore patterns and some bug fixes
  README.md
  bundled/tool/_debug_server.py
  bundled/tool/lsp_server.py
  bundled/tool/lsp_utils.py
  package-lock.json
  package.json
  package.nls.json
  requirements.txt
  src/common/constants.ts
  src/common/logging.ts
  src/common/python.ts
  src/common/server.ts
  src/common/settings.ts
  src/common/status.ts
  src/common/utilities.ts
  src/common/vscodeapi.ts
  src/extension.ts
  src/test/python_tests/lsp_test_client/defaults.py
  src/test/python_tests/lsp_test_client/session.py
  src/test/python_tests/lsp_test_client/utils.py
  src/test/python_tests/test_linting.py
  src/test/python_tests/test_path_specialization.py
Labels: feature-request
