Repository microsoft/vscode-flake8, pull requests merged in 2023-01, with the labels that each got.

#83 Remove PR Chat
  .github/workflows/pr-chat.yml
Labels: debt

#99 Update localization
  .github/workflows/pr-check.yml
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  package-lock.json
  package.json
  src/extension.ts
  src/setupNLS.ts
  webpack.config.js
Labels: debt

#102 Add support for legacy `python.linting.cwd` setting
  bundled/tool/_debug_server.py
  bundled/tool/lsp_jsonrpc.py
  bundled/tool/lsp_runner.py
  bundled/tool/lsp_server.py
  bundled/tool/lsp_utils.py
  package-lock.json
  package.json
  requirements.txt
  src/common/constants.ts
  src/common/settings.ts
  src/test/python_tests/lsp_test_client/session.py
  src/test/python_tests/lsp_test_client/utils.py
  src/test/python_tests/requirements.txt
  src/test/python_tests/test_code_actions.py
Labels: feature-request

#103 Set Dependabot Python version
  runtime.txt
Labels: dependencies, debt
