Repository microsoft/vscode-flake8, pull requests merged in 2023-03, with the labels that each got.

#126 Clean up and fixes from extension template
  .vscode/extensions.json
  .vscode/launch.json
  .vscodeignore
  bundled/tool/lsp_server.py
  package-lock.json
  package.json
  package.nls.json
  requirements.txt
  src/common/log/fileLogger.ts
  src/common/log/logging.ts
  src/common/log/outputChannelLogger.ts
  src/common/log/types.ts
  src/common/python.ts
  src/common/server.ts
  src/common/settings.ts
  src/common/utilities.ts
  src/common/vscodeapi.ts
  src/extension.ts
  src/test/python_tests/requirements.txt
  tsconfig.json
  tsfmt.json
Labels: debt

#127 Update version for release
  package-lock.json
  package.json
Labels: no-changelog

#128 Update main version for pre-release
  package-lock.json
  package.json
Labels: no-changelog

#131 fix typo in README.md
  README.md
Labels: bug

#138 Update all dependencies
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: no-changelog
