Repository microsoft/vscode-flake8, pull requests merged in 2023-11, with the labels that each got.

#245 Update version and packages for release
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: no-changelog

#251 Update main version for pre-release
  package-lock.json
  package.json
Labels: no-changelog

#254 Fix for `${fileDirname}` crash
  src/common/server.ts
Labels: bug

#256 Use fnmatch instead of pathlibs match
  bundled/tool/lsp_utils.py
Labels: bug

#255 Update Flake8 settings descriptions
  README.md
  package.json
  package.nls.json
Labels: documentation, debt

#257 Change the flake8 version string in `readme.md` to be pip compatible
  .gitignore
  README.md
  noxfile.py
Labels: debt
