Repository microsoft/vscode-flake8, pull requests merged in 2024-01, with the labels that each got.

#268 Add linting enable/disable functionality
  bundled/tool/lsp_server.py
  package.json
  package.nls.json
  src/common/settings.ts
  src/test/python_tests/test_linting.py
Labels: feature-request

#277 Update packages
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: debt

#278 Fix dependabot labels
  .github/dependabot.yml
Labels: no-changelog

#280 Add enabled setting to README
  README.md
  package.nls.json
Labels: no-changelog

#281 Add Flake8 issue tracker to README
  README.md
Labels: documentation, debt
