Repository microsoft/vscode-flake8, pull requests merged in 2025-02, with the labels that each got.

#334 Update packages for final python 3.8 release
  README.md
  bundled/tool/lsp_server.py
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.in
  src/test/python_tests/requirements.txt
Labels: debt

#335 update to version 2025.1.0-dev
  package-lock.json
  package.json
Labels: no-changelog

#336 fix: Bug where successive python changed events trigger creating multiple servers
  src/common/constants.ts
  src/common/python.ts
  src/common/server.ts
  src/common/settings.ts
  src/common/utilities.ts
  src/extension.ts
Labels: bug

#337 Update pipelines and requirements to min python 3.9
  .github/actions/build-vsix/action.yml
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  README.md
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  noxfile.py
  requirements.in
  requirements.txt
  runtime.txt
  src/test/python_tests/requirements.in
  src/test/python_tests/requirements.txt
Labels: debt
